using TagAndTrack.Backend.Items;

namespace TagAndTrack.Tests;

public class SpecimenItemTests
{
    [Fact]
    public void Type_IsSpecimen()
    {
        var item = new SpecimenItem();
        Assert.Equal(Item.ItemType.Specimen, item.Type);
    }

    [Fact]
    public void Constructor_SetsNameAndDescription()
    {
        var item = new SpecimenItem("ARC-1", "Fossil A", "A trilobite fossil");
        Assert.Equal("Fossil A", item.Name);
        Assert.Equal("A trilobite fossil", item.Description);
    }

    [Fact]
    public void ID_IsAutoGeneratedAndNonZero()
    {
        var item = new SpecimenItem();
        Assert.NotEqual(0UL, item.ID);
    }

    [Fact]
    public void TwoItems_HaveDistinctIDs()
    {
        var a = new SpecimenItem();
        var b = new SpecimenItem();
        Assert.NotEqual(a.ID, b.ID);
    }

    [Fact]
    public void QRID_ReturnsCorrectFormat()
    {
        var item = new SpecimenItem();
        Assert.Equal($"Specimen:{item.ID}", item.QRID);
    }

    [Fact]
    public void Status_DefaultsToFalse()
    {
        // bool default is false; Status is not explicitly set to true in constructors
        var item = new SpecimenItem();
        Assert.False(item.Status);
    }

    [Fact]
    public void Checkout_SetsStatusToFalse()
    {
        var item = new SpecimenItem();
        item.Checkin(); // ensure true first
        item.Checkout();
        Assert.False(item.Status);
    }

    [Fact]
    public void Checkin_SetsStatusToTrue()
    {
        var item = new SpecimenItem();
        item.Checkout();
        item.Checkin();
        Assert.True(item.Status);
    }
}
